# Generated by Django 2.2.6 on 2019-10-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecheck',
            name='after_commission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='balancecheck',
            name='commision_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='balancecheck',
            name='complete_cnt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='balancecheck',
            name='jingsu',
            field=models.IntegerField(),
        ),
    ]
