# Generated by Django 2.2.6 on 2019-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashDate', models.CharField(max_length=200)),
                ('cashShopName', models.CharField(max_length=200)),
                ('cashNumber', models.IntegerField(max_length=200)),
                ('cashType', models.IntegerField(max_length=200)),
                ('cashAmt', models.IntegerField(max_length=200)),
                ('cashTitle', models.IntegerField(max_length=200)),
            ],
        ),
    ]
