# Generated by Django 2.2.6 on 2019-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycash',
            name='cashAmt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mycash',
            name='cashNumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mycash',
            name='cashTitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mycash',
            name='cashType',
            field=models.CharField(max_length=200),
        ),
    ]
