# Generated by Django 2.2.6 on 2019-10-25 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('activity_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycheck',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
            preserve_default=False,
        ),
    ]
