# Generated by Django 2.2.6 on 2019-10-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='address_from',
        ),
    ]
