# Generated by Django 2.2.6 on 2019-10-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0004_orderlist_address_new_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='address_to',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='delivery_fee',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='distance',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='payment_amt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='payment_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='request',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='serial_num',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='time_limit',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
