# Generated by Django 2.2.6 on 2019-10-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0005_auto_20191023_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='status',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
